### ISSUE TITLE
Website is not screen friendly

### ISSUE THREAD

**Issue by ritwik12** [SWLivingstone/my_dev_portal#3]
Please make this website automatically adjustable for all screen sizes.
Some part of the website is getting cropped.
Use websites like 
http://quirktools.com/screenfly/
to test your website for different screen sizes.

**Comment by SWLivingstone** [comment]
I fixed the sidebar on the user dashboard to scale better for smaller screens.

I still need to come up with a solution for mobile screens.  It will likely involve replacing the sidebar with a dropdown menu.

**Comment by SWLivingstone** [comment]
I completely rebuilt the UI for the entire app and it should now work for most screen sizes.  However, it still does not work great on mobile devices.

**Comment by ritwik12** [comment]
@SWLivingstone It is working fine now, I also checked on my mobile and it looks great :)
